[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "methylator"
authors = [{name = "Elio", email = "eliof@posteo.net"}]
dynamic = ["version", "description"]
